apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git::ssh://git@github.com/calavelas/kustomize-template.git/deployment-component/deployment
- git::ssh://git@github.com/calavelas/kustomize-template.git/service-component/service

commonLabels:
  app.kubernetes.io/instance: service-test-1

components:
- git::ssh://git@github.com/calavelas/kustomize-template.git/configmap-component/configmap-env
# - git::ssh://git@github.com/calavelas/kustomize-template.git/configmap-component/configmap-file
- git::ssh://git@github.com/calavelas/kustomize-template.git/secret-component/secret-env
# - git::ssh://git@github.com/calavelas/kustomize-template.git/secret-component/secret-file

# patches:
# - target:
#     kind: Deployment
#   path: patches/replace-secret-mount.yaml

